---
abstract: bridge between IO::Lambda and Linux::Inotify2
author:
  - 'Dmitry Karasik <dmitry@karasik.eu.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Lambda-Inotify
no_index:
  directory:
    - t
    - inc
requires:
  IO::Lambda: 1.22
  Linux::Inotify2: 1.22
version: 1.01
